apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: prometheus
spec:
  selector:
    env: metrics
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30001