apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  capacity:
    storage: 10Gi 
  storageClassName: nfs
  accessModes:
  - ReadWriteMany 
  nfs: 
    path: /k8s/d1/prometheus
    server: 192.168.50.204
  persistentVolumeReclaimPolicy: Retain 